'use client'
import { createClient } from '@/lib/supabase/client'
import { usePathname, useRouter } from 'next/navigation'
import Link from 'next/link'
import { useState, useEffect } from 'react'
import { getUserPermissions, UserRole } from '@/lib/permissions'

export default function Navbar() {
  const pathname = usePathname(), router = useRouter(), supabase = createClient()
  const [menuOpen,setMenuOpen]=useState(false),[role,setRole]=useState<UserRole|null>(null)
  useEffect(()=>{getUserPermissions().then(p=>{const r=p.role==='coach'||p.role==='editor'||p.role==='entry_only'?'data_entry':p.role==='super_admin'?'superadmin':p.role;setRole(r);const allowed=['/combine','/combine-import','/roster-import','/schedule','/attendance'];if(r==='data_entry'&&!allowed.includes(pathname))router.replace('/combine')})},[pathname])
  async function handleLogout(){await supabase.auth.signOut();window.location.href='/auth/login'}
  const common=[{href:'/combine',label:'Annual Combine'},{href:'/combine-import',label:'Combine Import'},{href:'/schedule',label:'Schedule'},{href:'/attendance',label:'Attendance'}]
  const linksByRole:Record<string,{href:string;label:string}[]>={
    superadmin:[{href:'/dashboard',label:'Dashboard'},...common,{href:'/athlete-reports',label:'Report Cards'},{href:'/athletes',label:'Athletes'},{href:'/import',label:'Import'},{href:'/roster-import',label:'Roster Import'},{href:'/admin',label:'Admin'},{href:'/audit',label:'Audit Log'}],
    admin:[{href:'/dashboard',label:'Dashboard'},...common,{href:'/athlete-reports',label:'Report Cards'},{href:'/athletes',label:'Athletes'},{href:'/import',label:'Import'},{href:'/roster-import',label:'Roster Import'},{href:'/admin',label:'Admin'}],
    data_entry:[...common,{href:'/roster-import',label:'Roster Import'}],coach:[{href:'/combine',label:'Annual Combine'},{href:'/schedule',label:'Schedule'},{href:'/attendance',label:'Attendance'},{href:'/dashboard',label:'Dashboard'}],entry_only:[{href:'/combine',label:'Annual Combine'},{href:'/schedule',label:'Schedule'},{href:'/attendance',label:'Attendance'}]
  }
  const badgeMap:Record<string,{bg:string;border:string;color:string;label:string}>={superadmin:{bg:'rgba(239,68,68,0.15)',border:'rgba(239,68,68,0.4)',color:'#f87171',label:'SUPER ADMIN'},admin:{bg:'rgba(251,191,36,0.15)',border:'rgba(251,191,36,0.3)',color:'#fbbf24',label:'ADMIN'},data_entry:{bg:'rgba(59,130,246,0.1)',border:'rgba(59,130,246,0.25)',color:'#60a5fa',label:'DATA ENTRY'},coach:{bg:'rgba(59,130,246,0.1)',border:'rgba(59,130,246,0.25)',color:'#60a5fa',label:'DATA ENTRY'},entry_only:{bg:'rgba(52,211,153,0.1)',border:'rgba(52,211,153,0.25)',color:'#34d399',label:'ENTRY'}}
  const links=role?(linksByRole[role]||linksByRole.data_entry):[],badge=role?badgeMap[role]:null,isActive=(h:string)=>pathname===h||(pathname?.startsWith(h)&&h!=='/')
  const linkStyle=(h:string)=>({padding:'4px 7px',borderRadius:'6px',fontSize:'11px',fontWeight:500,textDecoration:'none',fontFamily:'var(--font-display)',letterSpacing:'0.03em',color:isActive(h)?'#60a5fa':'#64748b',background:isActive(h)?'rgba(59,130,246,0.1)':'transparent',border:`1px solid ${isActive(h)?'rgba(59,130,246,0.3)':'transparent'}`,display:'block',whiteSpace:'nowrap' as const})
  return <nav style={{background:'rgba(2,11,24,0.95)',borderBottom:'1px solid rgba(59,130,246,0.15)',backdropFilter:'blur(12px)',position:'sticky',top:0,zIndex:40}}><div style={{maxWidth:'1280px',margin:'0 auto',padding:'0 16px',display:'flex',alignItems:'center',justifyContent:'space-between',height:'52px',gap:'8px'}}><Link href={role==='data_entry'||role==='entry_only'?'/combine':'/dashboard'} style={{display:'flex',alignItems:'center',gap:'8px',textDecoration:'none',flexShrink:0}}><div style={{width:28,height:28,borderRadius:6,overflow:'hidden'}}><img src="/logo.jpg" alt="KMHA" style={{width:'100%',height:'100%',objectFit:'cover'}}/></div><span style={{color:'white',fontWeight:700,fontSize:13,letterSpacing:'0.1em',fontFamily:'var(--font-display)'}}>KMHA</span></Link><div style={{display:'flex',alignItems:'center',gap:'1px',flex:1,justifyContent:'center',overflow:'hidden'}} className="hidden-mobile">{links.map(l=><Link key={l.href} href={l.href} style={linkStyle(l.href)}>{l.label}</Link>)}{badge&&<span style={{marginLeft:4,padding:'2px 5px',borderRadius:4,fontSize:8,background:badge.bg,border:`1px solid ${badge.border}`,color:badge.color,fontFamily:'var(--font-display)',fontWeight:600,whiteSpace:'nowrap'}}>{badge.label}</span>}</div><button onClick={handleLogout} className="hidden-mobile" style={{padding:'4px 10px',borderRadius:6,fontSize:11,background:'transparent',border:'1px solid rgba(59,130,246,0.2)',color:'#475569',cursor:'pointer'}}>Sign Out</button><button onClick={()=>setMenuOpen(!menuOpen)} className="show-mobile" style={{background:'none',border:'none',color:'#64748b',fontSize:20,padding:4,display:'none'}}>{menuOpen?'✕':'☰'}</button></div>{menuOpen&&<div className="show-mobile" style={{background:'rgba(2,11,24,0.98)',borderTop:'1px solid rgba(59,130,246,0.1)',padding:'12px 16px'}}>{links.map(l=><Link key={l.href} href={l.href} onClick={()=>setMenuOpen(false)} style={{...linkStyle(l.href),padding:'10px 14px',marginBottom:4}}>{l.label}</Link>)}<button onClick={handleLogout} style={{width:'100%',marginTop:8,padding:10,borderRadius:6,fontSize:12,background:'transparent',border:'1px solid rgba(59,130,246,0.2)',color:'#475569',textAlign:'left'}}>Sign Out</button></div>}<style>{`@media(max-width:768px){.hidden-mobile{display:none!important}.show-mobile{display:block!important}}@media(min-width:769px){.show-mobile{display:none!important}.hidden-mobile{display:flex!important}}`}</style></nav>
}
