'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import * as XLSX from 'xlsx'
import { TEAMS } from '@/types'

type Row = { athlete_name:string; raw_attendance:number; adjusted_attendance:number; matched?:boolean; athlete_id?:string }
type Detection = { team:string; season:string; firstDate:string; lastDate:string; sessions:number }
const norm=(v:any)=>String(v??'').trim().toLowerCase().replace(/[^a-z0-9]/g,'')
const pct=(v:any)=>{ if(typeof v==='number') return v<=1?v*100:v; const s=String(v??'').replace('%','').trim(); const n=Number(s); return Number.isFinite(n)?(n<=1&&String(v).includes('.')?n*100:n):NaN }
const fmt=(d:Date)=>d.toISOString().slice(0,10)
function excelDate(v:any){ if(v instanceof Date&&!isNaN(v.getTime())) return v; if(typeof v==='number'&&v>30000&&v<70000){const o=XLSX.SSF.parse_date_code(v);if(o)return new Date(o.y,o.m-1,o.d)} const d=new Date(String(v||''));return isNaN(d.getTime())?null:d }
function seasonFromDates(ds:Date[]){ if(!ds.length)return '2026-2027'; const d=ds.sort((a,b)=>a.getTime()-b.getTime())[0]; const y=d.getFullYear(); return d.getMonth()>=7?`${y}-${y+1}`:`${y-1}-${y}` }
function detectTeam(data:any[][], fileName:string){ const hay=[fileName,...data.slice(0,20).flat().map(String)].join(' ').toUpperCase().replace(/[^A-Z0-9]/g,''); return TEAMS.find(t=>hay.includes(t.toUpperCase().replace(/[^A-Z0-9]/g,'')))||'' }

export default function AttendanceImportPage(){
 const[team,setTeam]=useState(''),[season,setSeason]=useState('2026-2027'),[rows,setRows]=useState<Row[]>([]),[fileName,setFileName]=useState(''),[status,setStatus]=useState(''),[saving,setSaving]=useState(false),[detection,setDetection]=useState<Detection|null>(null)
 const matched=useMemo(()=>rows.filter(r=>r.matched).length,[rows])
 async function matchRows(parsed:{name:string;raw:number}[], detectedTeam:string, detectedSeason:string){
  if(!detectedTeam){setRows(parsed.map(x=>({athlete_name:x.name,raw_attendance:Number(x.raw.toFixed(1)),adjusted_attendance:Math.min(100,Math.ceil(x.raw+7))})));return}
  const athletes=await fetch(`/api/athletes?team=${encodeURIComponent(detectedTeam)}&season=${encodeURIComponent(detectedSeason)}&activeOnly=true`).then(r=>r.json())
  const list=Array.isArray(athletes)?athletes:[]
  setRows(parsed.map(x=>{const a=list.find((z:any)=>norm(`${z.first_name}${z.last_name}`)===norm(x.name)||norm(`${z.last_name}${z.first_name}`)===norm(x.name));return{athlete_name:x.name,raw_attendance:Number(x.raw.toFixed(1)),adjusted_attendance:Math.min(100,Math.ceil(x.raw+7)),matched:!!a,athlete_id:a?.id}}))
 }
 async function readFile(file:File){
  setStatus('Reading TeamBuildr file...');setFileName(file.name);setRows([])
  const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});const ws=wb.Sheets[wb.SheetNames[0]];const data:any[][]=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:true})
  if(!data.length){setStatus('No rows found in file.');return}
  let header=-1,nameCol=-1,attCol=-1
  for(let i=0;i<Math.min(data.length,40);i++){const h=data[i].map(x=>String(x).trim().toLowerCase());const n=h.findIndex(x=>x==='athlete'||x==='athlete name'||x==='name'||x.includes('athlete'));const a=h.findIndex(x=>x.includes('attendance')||x.includes('attend %')||x==='attendance %');if(n>=0&&a>=0){header=i;nameCol=n;attCol=a;break}}
  if(header<0){setStatus('Could not find Athlete/Name and Attendance columns.');return}
  const parsed=data.slice(header+1).map(r=>({name:String(r[nameCol]||'').trim(),raw:pct(r[attCol])})).filter(x=>x.name&&Number.isFinite(x.raw))
  const dates:Date[]=[];data.forEach(r=>r.forEach(v=>{const d=excelDate(v);if(d&&d.getFullYear()>=2024&&d.getFullYear()<=2030)dates.push(d)}));const uniqueDates=[...new Set(dates.map(fmt))].sort();const detectedTeam=detectTeam(data,file.name)||team;const detectedSeason=seasonFromDates(dates)
  if(detectedTeam)setTeam(detectedTeam);setSeason(detectedSeason);setDetection({team:detectedTeam,season:detectedSeason,firstDate:uniqueDates[0]||'',lastDate:uniqueDates[uniqueDates.length-1]||'',sessions:uniqueDates.length})
  await matchRows(parsed,detectedTeam,detectedSeason);setStatus(`Auto-detected ${detectedTeam||'team not found'} · ${detectedSeason} · ${uniqueDates.length||'unknown'} sessions. Parsed ${parsed.length} athletes.`)
 }
 async function save(){if(!team||!rows.length)return;setSaving(true);setStatus('Saving attendance import...');const res=await fetch('/api/attendance-import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({team,season,source_file:fileName,first_date:detection?.firstDate,last_date:detection?.lastDate,session_count:detection?.sessions,rows:rows.filter(r=>r.matched)})});const j=await res.json().catch(()=>({}));setSaving(false);setStatus(res.ok?`Saved ${j.saved??matched} attendance records.`:`Save failed: ${j.error||res.statusText}`)}
 const card={background:'rgba(10,20,40,.88)',border:'1px solid rgba(59,130,246,.16)',borderRadius:12}
 return <div style={{paddingBottom:48,maxWidth:1180,margin:'0 auto'}}>
  <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,padding:'18px 0',borderBottom:'1px solid rgba(59,130,246,.12)',marginBottom:22}}><div><h1 style={{margin:0,color:'white',fontSize:30,letterSpacing:'.05em'}}>ATTENDANCE IMPORT</h1><p style={{color:'#64748b',margin:'5px 0 0',fontSize:13}}>TeamBuildr attendance → athlete report cards</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Link href="/dashboard" style={{padding:'8px 12px',border:'1px solid rgba(59,130,246,.2)',borderRadius:7,color:'#94a3b8',textDecoration:'none',fontSize:12}}>Dashboard</Link><Link href="/athlete-reports" style={{padding:'8px 12px',border:'1px solid rgba(59,130,246,.2)',borderRadius:7,color:'#94a3b8',textDecoration:'none',fontSize:12}}>Report Cards</Link><Link href="/attendance" style={{padding:'8px 12px',border:'1px solid rgba(59,130,246,.2)',borderRadius:7,color:'#94a3b8',textDecoration:'none',fontSize:12}}>Attendance</Link></div></div>
  <div style={{...card,padding:18,marginBottom:16}}><div style={{fontSize:11,color:'#60a5fa',fontWeight:700,letterSpacing:'.08em',marginBottom:12}}>1 · UPLOAD TEAMBUILDR FILE</div><label style={{display:'block',border:'1px dashed rgba(96,165,250,.35)',borderRadius:10,padding:'24px 18px',textAlign:'center',cursor:'pointer',background:'rgba(59,130,246,.04)'}}><div style={{color:'#e2e8f0',fontWeight:700,marginBottom:5}}>{fileName||'Choose TeamBuildr Excel file'}</div><div style={{color:'#64748b',fontSize:12}}>.xlsx, .xls or .csv · team, season and session dates auto-detected</div><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>e.target.files?.[0]&&readFile(e.target.files[0])} style={{display:'none'}}/></label></div>
  <div style={{...card,padding:18,marginBottom:16}}><div style={{fontSize:11,color:'#60a5fa',fontWeight:700,letterSpacing:'.08em',marginBottom:12}}>2 · AUTO-DETECTED IMPORT DETAILS</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12}}><div><label style={{display:'block',fontSize:10,color:'#64748b',marginBottom:5}}>TEAM</label><select className="kmha-select w-full" value={team} onChange={e=>setTeam(e.target.value)}><option value="">Not detected</option>{TEAMS.map(t=><option key={t}>{t}</option>)}</select></div><div><label style={{display:'block',fontSize:10,color:'#64748b',marginBottom:5}}>SEASON</label><input className="kmha-input w-full" value={season} onChange={e=>setSeason(e.target.value)}/></div><div><label style={{display:'block',fontSize:10,color:'#64748b',marginBottom:5}}>FIRST SESSION</label><div style={{padding:'9px 10px',color:'#e2e8f0'}}>{detection?.firstDate||'—'}</div></div><div><label style={{display:'block',fontSize:10,color:'#64748b',marginBottom:5}}>LAST SESSION</label><div style={{padding:'9px 10px',color:'#e2e8f0'}}>{detection?.lastDate||'—'}</div></div><div><label style={{display:'block',fontSize:10,color:'#64748b',marginBottom:5}}>SESSIONS</label><div style={{padding:'9px 10px',color:'#e2e8f0',fontWeight:700}}>{detection?.sessions||'—'}</div></div></div></div>
  {status&&<div style={{padding:'11px 14px',marginBottom:16,borderRadius:8,background:'rgba(59,130,246,.08)',border:'1px solid rgba(59,130,246,.18)',color:'#93c5fd',fontSize:13}}>{status}</div>}
  {rows.length>0&&<div style={{...card,overflow:'hidden'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'14px 16px',borderBottom:'1px solid rgba(59,130,246,.1)'}}><div><div style={{color:'white',fontWeight:700}}>3 · PREVIEW IMPORT</div><div style={{color:'#64748b',fontSize:12,marginTop:3}}>{rows.length} athletes · {matched} matched · {rows.length-matched} unmatched</div></div><button disabled={saving||!team||matched===0} onClick={save} style={{padding:'9px 16px',borderRadius:7,border:0,background:'#2563eb',color:'white',fontWeight:700,cursor:'pointer',opacity:(saving||!team||matched===0)?.55:1}}>{saving?'Saving...':'Confirm Import'}</button></div><div style={{overflowX:'auto',maxHeight:520}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:13}}><thead style={{position:'sticky',top:0,background:'#071226'}}><tr style={{color:'#64748b'}}><th style={{padding:10,textAlign:'left'}}>Athlete</th><th>Raw Attendance</th><th>Report Card (+7)</th><th>Roster Match</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i} style={{borderTop:'1px solid rgba(59,130,246,.07)',color:'#e2e8f0'}}><td style={{padding:10}}>{r.athlete_name}</td><td style={{textAlign:'center'}}>{r.raw_attendance.toFixed(1)}%</td><td style={{textAlign:'center',fontWeight:700}}>{r.adjusted_attendance}%</td><td style={{textAlign:'center',color:r.matched?'#34d399':'#f87171',fontWeight:600}}>{r.matched?'Matched':'Not matched'}</td></tr>)}</tbody></table></div></div>}
 </div>
}
